server:
  # ????????????????????????????????docker run???-e???maven package???????????mvn test
  port: ${tomcatSeverPort}
  servlet:
    context-path: /tomcat
  tomcat:
    # ????????????????????????????????docker run???-e??
    accept-count: ${maxTomcatAcceptCount}
    threads:
      # ????????????????????????????????docker run???-e??
      max: ${maxTomcatThreadNum}