FROM java:9

MAINTAINER 18315107186@189.cn

#EXPOSE 8010

ADD ./target/yuezhi-api-manager-1.0-SNAPSHOT.jar ./yuezhi-api-manager-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","yuezhi-api-manager-1.0-SNAPSHOT.jar"]




