# 服务打包
version: "2"
services:
#  yuezhi-api-manager:
#    image: yuezhi/yuezhi-api-manager
#    ports:
#      - "1113:1113"
#    external_links:
#      - "config"
#      - "eurekaserver:peer1"
#  service_b:
#    image: cloud_test/service_b
#    ports:
#      - "1114:1114"
#    external_links:
#      - "eurekaserver:peer1"
#      - "service_a"

  yuezhi-basic-monitor:
    image: yuezhi-basic-monitor-1.0
    ports:
      - "8001:8001"
    tty: true
    network_mode: bridge
    restart: always
  yuezhi-api-manager:
    image: yuezhi-api-manager-1.0
    ports:
      - "8081:8081"
    tty: true
    network_mode: bridge
    restart: always
  yuezhi-service-business:
    image: yuezhi-service-business-1.0
    ports:
      - "8084:8084"
    tty: true
    network_mode: bridge
    restart: always